export { ihheaderStyles } from "./ihhead";
export { ihbodyStyles } from "./ihbody";
export { ihhomeBannerStyles } from "./ihhome_banner";
export { annoumentStyles } from "./announcement";
export { founderStyles } from "./founder";
export { upcomingTrekStyles } from "./upcoming_trek";
export { whyTrekWithStyles } from "./whytrek";
export { whatTrekkerSayStyles } from "./what_trekker_say";
export { experimentStyles } from "./experiment_learning";