export { default as BestTrekToDo } from "./BestTrekToDo";
export { default as UpComingTreks } from "./Upcoming_Treks";
// export { default as UCFeaturedTreks } from "./Featured_Treks";
export { default as UCOpenForSmallGroup } from "./Open_For_Small_Group";
// export { default as UCWhyTreks } from "./UC_Why_Terks";
export { default as UCAutnumTreks } from "./UC_Autumn_Treks";
export { default as UCFamilyTreks } from "./UC_Family_Treks";
export { default as UCWinterTreks } from "./UC_Winter_Treks";
export { default as UCTreksToDo } from "./UC_Treks_To_Do";
export { default as UCDYITreks } from "./UC_Dyi_Treks";
export { default as UcCrossTrek } from "./UcCrossTrek";
export { default as AllIndiaHikes } from "./AllIndiaHikes";
